<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>MobileUITests</RootNamespace>
		<AssemblyName>MobileUITests</AssemblyName>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Appium.WebDriver" />
		<PackageReference Include="Codeuctivity.ImageSharpCompare" />
		<PackageReference Include="Microsoft.Testing.Platform" />
		<PackageReference Include="SixLabors.ImageSharp" />
	</ItemGroup>
</Project>
